name: Build and deploy Python app to Azure Web App - form-page

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Unit Tests (test_unit.py)
        run: |
          source venv/bin/activate
          pytest tests/test_unit.py --maxfail=5 --disable-warnings

      - name: Set up Chrome for Selenium Tests
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Run Selenium Tests (selenium.py)
        run: |
          source venv/bin/activate
          pytest tests/selenium.py --maxfail=5 --disable-warnings

      - name: Zip artifact for deployment
        run: |
          zip release.zip ./* -r
          
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3973EFBB0D2E4F6DA9FED1EA19D27E3F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_65404AE89DBE45A09284D29008389E32 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5DBBE79E6EDA4F4DAFF980B38D8F717B }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'form-page'
          slot-name: 'Production'
